# alias
alias e=emacs
alias ec='emacsclient -t'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias tmux='tmux -f ~/.config/tmux/tmux.conf'
if [ "$(uname -n)" == "Lap1077" ]; then
  alias open=explorer.exe
fi

# readline
INPUTRC=~/.config/readline/inputrc

# vim
EDITOR=vim; export EDITOR;
VIMINIT='let $MYVIMRC="~/.config/vim/vimrc" | source $MYVIMRC'; export VIMINIT

# ssh
SSH_ENV="$HOME/.ssh/env"
[ -f $SSH_ENV ] && . $SSH_ENV
start-ssh-agent () {
  echo "Starting new SSH agent..."
  ssh-agent | sed '/^echo/d' > $SSH_ENV
  . $SSH_ENV
  ssh-add
}
