so $VIMRUNTIME/defaults.vim

set bdir-=.
set dir -=.
set hls

if has('gui_running')
	if has('win32')
		set guioptions-=T
		set guifont=Cascadia_Mono:h12
	endif
	colorscheme onehalfdark
elseif exists('+termguicolors')
	" tmux {
	let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
	let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
	" }
	set termguicolors
	colorscheme onehalfdark
endif
